import {buildFactory} from "./buildFactory";

interface MyType {
    myRequiredField: number;
    myOptionalField?: number;
}

describe("a function generated by buildFactory", () => {
    it("returns the default object when called with no parameters", () => {
        const myDefaultObject: MyType = {
            myRequiredField: 1,
            myOptionalField: 2
        };

        const myFactory = buildFactory<MyType>(myDefaultObject);

        expect(myFactory()).toEqual(myDefaultObject);
    });
});